inherit_from: .rubocop_todo.yml

# inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Gemspec/DevelopmentDependencies:
  Enabled: false

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/Documentation:
  Exclude:
    - 'test/**/*'

Style/EmptyMethod:
  EnforcedStyle: expanded
  Enabled: true

Style/FormatString:
  EnforcedStyle: sprintf

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/FrozenStringLiteralComment:
  Exclude:
    - 'lib/aozora2html.rb'

Style/RedundantPercentQ:
  Enabled: false

Style/PercentQLiterals:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/ZeroLengthPredicate:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 500

Lint/EmptyClass:
  AllowComments: true

Lint/InheritException:
  Enabled: false

Metrics/AbcSize:
  Enabled: true
  Max: 260.05

Metrics/BlockLength:
  Enabled: true
  Max: 150

Metrics/BlockNesting:
  Enabled: true
  Max: 10

Metrics/ClassLength:
  Enabled: true
  Max: 2000

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 100

Metrics/MethodLength:
  Enabled: true
  Max: 200

Metrics/ModuleLength:
  Enabled: true
  Max: 200

Metrics/ParameterLists:
  Enabled: true
  Max: 10

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 100
