inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/EmptyMethod:
  EnforcedStyle: expanded
  Enabled: true

Style/RedundantPercentQ:
  Enabled: false

Style/PercentQLiterals:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/ClassCheck:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 500

Metrics/AbcSize:
  Enabled: true
  Max: 260.05

Metrics/BlockLength:
  Enabled: true
  Max: 150

Metrics/BlockNesting:
  Enabled: true
  Max: 10

Metrics/ClassLength:
  Enabled: true
  Max: 2000

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 100

Metrics/MethodLength:
  Enabled: true
  Max: 200

Metrics/ModuleLength:
  Enabled: true
  Max: 100

Metrics/ParameterLists:
  Enabled: true
  Max: 10

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 100
