# Check if Ruby codes pass tests.
#
# Reference:
#   - https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Test

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.2', '3.1', '3.0', '2.7' ]
        os: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
        - os: windows-latest
          ruby: '3.1'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build and test with Rake
      shell: bash
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec rake
